# Generated by Django 4.0.4 on 2022-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('received_at', models.DateField(verbose_name='Дата поступления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Цена товара')),
                ('measure_unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='Имя поставщика')),
            ],
        ),
    ]
